title: Web Design Basics Fall 2018
email: seth@channel.studio
description: >- # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://courses.channel.studio/PSAM1208_FALL2018" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown

plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock

include: 
  - _pages

sass:
  style: compressed
